spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/Incidentor
    username: postgres
    password: postgres
    flyway:
      enabled: true
    jpa:
      show-sql: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        data: DEBUG