spring:
  datasource:
    url: jdbc:postgresql://localhost:5430/Incidentor
    username: postgres
    password: postgres
    flyway:
      enabled: true

logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    logging:
      level:
        org:
          springframework:
            security: DEBUG